project:
  type: book

book:
  title: "Aprendizaje Máquina 2025"
  author: "Felipe González"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-principios-supervisado.qmd
  appendices:
    - 99-referencias.qmd

bibliography: referencias/book.bib

format:
  html:
    theme: journal
    lang: es
    font-size: 1.1em
    code-fold: false



